features/search.feature
features/support/steps.js
features/support/world.js
package-lock.json
package.json

(https://ilabs-capco.atlassian.net/browse/BENCH-1152)
Added a the Cucumber and PlayWright dependency as well as a working test.
To review run the application locally and then npm install, npm run cucumberTest 

Bench-1152 added playwright, cucumber and a working test

---

src/components/Footer/Footer.tsx
src/components/Footer/_tests_/Footer.test.tsx
src/components/Footer/_tests_/__snapshots__/Footer.test.tsx.snap
src/components/Menu/Menu.tsx
src/components/Menu/_tests_/__snapshots__/Menu.test.tsx.snap

Added function to update year & updated the unit tests

---

src/components/Accordion/Accordion.tsx
src/components/Accordion/_tests_/__snapshots__/Accordion.test.tsx.snap
src/containers/ContentPage/ContentPage.tsx

edit the content

---

features/mobile/flutter.feature
features/mobile/gradleMobile.feature
features/mobile/ionic.feature
features/mobile/javaMobile.feature
features/mobile/swift.feature
features/support/steps.js

Added tests to finish Mobile Category

---

features/frontend/typescript.feature
features/support/steps.js
features/support/world.js

Made browser into a global variable and then closed it

---

src/components/RadarKey/RadarKey.tsx
src/components/RadarKey/styles/index.tsx

Improved the key interaction

---

src/components/Radar/_tests_/__snapshots__/Radar.test.tsx.snap
src/containers/CategoryPage/_tests_/__snapshots__/CategoryPage.test.tsx.snap
src/data/data.tsx

updated image urls

---

features/backend/java.feature
features/backend/node.feature
features/backend/scala.feature
features/cloudAndPlatforms/aws.feature
features/databases/mongoDb.feature
features/databases/mySql.feature
features/databases/postgres.feature
features/devops/jenkins.feature
features/frontend/react.feature
features/frontend/typescript.feature
features/support/steps.js

Added 16 tests for content categories

---

src/components/Content/Content.tsx
src/helpers/_tests_/helper.test.tsx
src/helpers/helpers.tsx

[*BENCH-1235*](https://ilabs-capco.atlassian.net/browse/BENCH-1235)
Added a helper function to capitalize the first character for accordion descriptions

BENCH-1235 add filter to capitalize first character

---

features/backend/java.feature
src/data/content/backend.ts
src/data/content/mobile.ts

[*BENCH-1234*](https://ilabs-capco.atlassian.net/browse/BENCH-1234)
[*BENCH-1213*](https://ilabs-capco.atlassian.net/browse/BENCH-1213)
Fix J in Java page
Fix Bloc in Flutter page

BENCH-1234 BENCH-1213 typo bug fixes

---

package-lock.json
package.json
src/components/Accordion/_tests_/__snapshots__/Accordion.test.tsx.snap
src/components/ProjectItem/ProjectItem.tsx
src/components/ProjectItem/_tests_/__snapshots__/ProjectItem.test.tsx.snap
src/components/ProjectItem/styles/index.tsx
src/components/ProjectPageLink/ProjectTechnologyLink.tsx
src/containers/ProjectPage/ProjectPage.tsx

https://ilabs-capco.atlassian.net/browse/BENCH-1237
* Fetched GitHub OSS projects with github API
* Displayed project items as best possible without further enhancements to key technology data
* Displayed placeholder image as a temporary fix to avoid blocks reliant on external factors

Bench 1237 display oss projects

---

src/data/content/backend.ts

https://ilabs-capco.atlassian.net/browse/BENCH-1275
Image link broken on Node technology page

fixed broken logo link

---

src/components/Radar/Radar.tsx

https://ilabs-capco.atlassian.net/browse/BENCH-1277
move your cursor into the Mobile section, then drag your cursor to the top left of the page, your cursor is not on Mobile section anymore but the Mobile section is being focused/highlighted like your cursor is there.

fixed hover issue on radar

---

package-lock.json
src/components/Accordion/_tests_/__snapshots__/Accordion.test.tsx.snap
src/components/Content/styles/index.tsx
src/containers/ProjectPage/ProjectPage.tsx

https://ilabs-capco.atlassian.net/browse/BENCH-1293
1. The Accordion view text is split into 2 lines even though there seems to be space towards the right.
2. Some of the accordions have empty content when clicked, maybe these need not be displayed as accordions.
3. Need to verify the background color, it appears white 

fixed accordion css issue

---

src/components/ProjectItem/ProjectItem.tsx
src/components/ProjectPageLink/ProjectPageLink.tsx
src/components/Tabs/Tabs.tsx
src/components/Tabs/styles/index.tsx
src/containers/App/App.tsx
src/containers/ContentPage/_tests_/__snapshots__/ContentPage.test.tsx.snap
src/containers/ProjectPage/ProjectPage.tsx

https://ilabs-capco.atlassian.net/browse/BENCH-1302
The tab for Client projects should be enabled only when there are projects to show under Client project
The tab for OSS project should be enabled only when there are projects to show under OSS project

Disabled tabs on zero results

---

public/index.html
src/components/ProjectItem/styles/index.tsx
src/components/ProjectPageLink/styles/index.tsx

https://ilabs-capco.atlassian.net/browse/BENCH-1295
Made the fonts uniform across the app

fonts updated

---

package-lock.json
src/components/ComponentNavButton/ContentNavButton.tsx
src/containers/ContentPage/_tests_/__snapshots__/ContentPage.test.tsx.snap

https://ilabs-capco.atlassian.net/browse/BENCH-1276
Clicking the label “Next“ or “Previous“ will take you all the way to the top of the page

Fixed previous and next label click events

---

src/components/ProjectItem/ProjectItem.tsx
src/images/externallink.svg

[*Add a link to the JIRA ticket here.*](https://ilabs-capco.atlassian.net/browse/BENCH-1346)
Added svg to github repo link
- [X ] This PR is ready for review.

Bench 1346

---

src/data/data.tsx

[*https://ilabs-capco.atlassian.net/browse/BENCH-1362*](https://ilabs-capco.atlassian.net/browse/BENCH-1362)

remove selenium and add flutter to category

---

src/data/content/backend.ts
src/data/content/cloud.ts
src/data/content/databases.ts
src/data/content/devops.ts
src/data/content/mobile.ts

https://ilabs-capco.atlassian.net/browse/BENCH-1366
Inconsistency with capitalised sub-headings on technology pages

capitalised sub-headings in technology pages

---

src/components/BreadCrumb/_test_/__snapshots__/index.test.tsx.snap
src/components/BreadCrumb/index.tsx
src/containers/ProjectPage/_tests_/__snapshots__/ProjectPage.test.tsx.snap

https://ilabs-capco.atlassian.net/browse/BENCH-1354
The breadcrumb does not navigate to the correct page as indicated in the URL.

unsigned fix

---

src/components/ProjectItem/_tests_/__snapshots__/ProjectItem.test.tsx.snap
src/components/Radar/_tests_/__snapshots__/Radar.test.tsx.snap
src/containers/CategoryPage/_tests_/__snapshots__/CategoryPage.test.tsx.snap
src/containers/ContentPage/_tests_/__snapshots__/ContentPage.test.tsx.snap
src/containers/ProjectPage/_tests_/__snapshots__/ProjectPage.test.tsx.snap
src/data/content/quality.ts
src/data/data.tsx
src/data/projects/ClientProjects.ts

https://ilabs-capco.atlassian.net/browse/BENCH-1372
Include content from [here](https://capcoinc.sharepoint.com/sites/UKDigitalEngineering/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=eJi2yR&cid=3bab613c%2Dbab5%2D4101%2Dbd8c%2Daf6c68883907&RootFolder=%2Fsites%2FUKDigitalEngineering%2FShared%20Documents%2FTech%20Radar&FolderCTID=0x012000C3B42864821D1347887889DDE994C8C0) for the topic. 
Acceptance Criteria:
Content page should open up from the main radar
Content page link should be enabled in the Quality Engineering page
Any relevant projects should be linked under View Projects
*Screenshots can be …

added AXE content to the tedar

---

src/components/ProjectItem/ProjectItem.tsx
src/components/ProjectItem/_tests_/__snapshots__/ProjectItem.test.tsx.snap
src/containers/ProjectPage/_tests_/__snapshots__/ProjectPage.test.tsx.snap

only show key technologies that exist

---

package-lock.json
package.json
src/components/Content/Content.tsx
src/components/Tabs/Tabs.tsx
src/containers/CategoryPage/CategoryPage.tsx
src/containers/ContentPage/ContentPage.tsx
src/containers/ProjectPage/ProjectPage.tsx
src/containers/ProjectPage/_tests_/ProjectPage.test.tsx
src/containers/ProjectPage/_tests_/__snapshots__/ProjectPage.test.tsx.snap

https://ilabs-capco.atlassian.net/browse/BENCH-1458

BENCH-1458 fixed testing messages

---

README.md

BENCH-1718 - update CI/CD information to README

---

package.json
src/components/Accordion/_tests_/__snapshots__/Accordion.test.tsx.snap
src/components/Button/_tests_/__snapshots__/StyledButton.test.tsx.snap
src/components/CategoryListItem/_tests_/__snapshots__/CategoryListItem.test.tsx.snap
src/components/Footer/_tests_/__snapshots__/Footer.test.tsx.snap
src/components/Menu/_tests_/__snapshots__/Menu.test.tsx.snap
src/components/ProjectItem/_tests_/__snapshots__/ProjectItem.test.tsx.snap
src/components/Radar/_tests_/__snapshots__/Radar.test.tsx.snap
src/containers/CategoryPage/_tests_/__snapshots__/CategoryPage.test.tsx.snap
src/containers/ContentPage/_tests_/__snapshots__/ContentPage.test.tsx.snap
src/containers/ProjectPage/_tests_/__snapshots__/ProjectPage.test.tsx.snap
src/data/content/frontend.ts
src/data/data.tsx

[*Add a link to the JIRA ticket here.*](https://ilabs-capco.atlassian.net/browse/BENCH-1710)

BENCH-1710 added frontend content

---

src/data/content/backend.ts
src/data/data.tsx

[BENCH-1711](https://ilabs-capco.atlassian.net/browse/BENCH-1711)
Adds all missing content in the backend section. Kotlin page is half done and still needs completing, I will create a new ticket for this.

Backend content added

---

src/components/ProjectItem/_tests_/__snapshots__/ProjectItem.test.tsx.snap
src/components/Radar/_tests_/__snapshots__/Radar.test.tsx.snap
src/containers/CategoryPage/_tests_/__snapshots__/CategoryPage.test.tsx.snap
src/containers/ProjectPage/_tests_/__snapshots__/ProjectPage.test.tsx.snap
src/data/content/backend.ts

[*Add a link to the JIRA ticket here.*](https://ilabs-capco.atlassian.net/browse/BENCH-1741)

BENCH-1741 backend segment content

---

src/data/content/quality.ts

https://ilabs-capco.atlassian.net/browse/BENCH-1735
Removed the broken image link in selenium page.
- [x ] This PR is ready for review.
- [ x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors.
- [ x] All existing and new tests are passing.
- [ x] My PR meets the acceptance criteria as outlined by my ticket.
- [ x] I updated/added relevant documentation and comments (docs start with `///` and comments with `//`).
- [ x] Static analysis (e.g. Snyk) does not report any problems on my PR.

remove broken image link

---

src/data/content/quality.ts
src/data/data.tsx

BENCH-1736: Update content of JMeter

---

src/data/projects/ClientProjects.ts

[*Add a link to the JIRA ticket here.*
](https://ilabs-capco.atlassian.net/browse/BENCH-1762) 
add Kafka to the project tech array
- [ x ] This PR is ready for review.

add Kafka to tech array of project

---

src/data/content/integration.ts
src/data/data.tsx

Adding Kafka content

---

src/data/projects/ClientProjects.ts
src/images/ClientProjects/index.ts

Added new project details for Apache Hadoop

---

src/data/content/devops.ts
src/data/data.tsx

Added Consul content

---

src/data/content/devops.ts
src/data/data.tsx

Added documentation for Packer

---

src/data/content/devops.ts
src/data/data.tsx

Added Twistlock documentation

---

src/data/content/devops.ts
src/data/data.tsx

Added Ansible documentatio

---

src/data/projects/ClientProjects.ts

*[BENCH-1765: Integration Segment Preferred Tech. has no Linked Project - Rest.](https://ilabs-capco.atlassian.net/browse/BENCH-1765)*
*Added linked project to Rest technology*

Added linked project to Rest technology

---

src/data/projects/ClientProjects.ts

Added Gradle Mobile project

---

src/data/projects/ClientProjects.ts
src/images/ClientProjects/index.ts

*[Added missing projects for few techs.(https://ilabs-capco.atlassian.net/browse/BENCH-1810)](https://ilabs-capco.atlassian.net/browse/BENCH-1105)*
*Added missing projects for OpenAPI, TeamCity, PCF and ActiveMQ*

Added projects for ActiveMQ, OpenAPI, TeamCity and PCF

---

.gitignore
.nycrc
README.md
package-lock.json
package.json

Bench 1177 add coverage badge

---

.nycrc
README.md

add badge to README

---

package-lock.json
src/components/Accordion/_tests_/__snapshots__/Accordion.test.tsx.snap
src/components/Button/_tests_/__snapshots__/StyledButton.test.tsx.snap
src/components/CategoryListItem/_tests_/__snapshots__/CategoryListItem.test.tsx.snap
src/components/Footer/_tests_/__snapshots__/Footer.test.tsx.snap
src/components/Menu/_tests_/__snapshots__/Menu.test.tsx.snap
src/components/ProjectItem/_tests_/__snapshots__/ProjectItem.test.tsx.snap
src/components/Radar/_tests_/Radar.test.tsx
src/components/Radar/_tests_/__snapshots__/Radar.test.tsx.snap
src/containers/CategoryPage/_tests_/__snapshots__/CategoryPage.test.tsx.snap
src/containers/ContentPage/_tests_/__snapshots__/ContentPage.test.tsx.snap
src/containers/ProjectPage/ProjectPage.tsx
src/containers/ProjectPage/_tests_/__snapshots__/ProjectPage.test.tsx.snap

Bench 1851 fix failed jest tests

---

src/data/projects/ClientProjects.ts

*[Quality Engineering Segment Missing Project Link - Selenium](https://ilabs-capco.atlassian.net/browse/BENCH-1777).*
*Added missing project for Selenium technology.*

Added missing project for Selenium tech

---

src/data/projects/ClientProjects.ts

*[Quality Engineering Segment Missing Project Link - SauceLabs.](https://ilabs-capco.atlassian.net/browse/BENCH-1859)*
*Added missing project to Sauce Labs technology.*

added missing project to sauce labs tech

---

src/containers/ProjectPage/styles/index.tsx
src/data/content/backend.ts
src/data/content/databases.ts
src/data/content/devops.ts
src/data/content/frontend.ts
src/data/content/mobile.ts
src/data/content/quality.ts

https://ilabs-capco.atlassian.net/browse/BENCH-1922
Source references were added to wherever missing in technology content pages - this gives content pages validity and integrity. Pages with minimal content were add to - but can be modified further if still insufficient.

Bench 1922 sources add

---

src/components/ProjectItem/ProjectItem.tsx
src/components/ProjectItem/_tests_/__snapshots__/ProjectItem.test.tsx.snap
src/containers/ContentPage/_tests_/__snapshots__/ContentPage.test.tsx.snap
src/containers/ProjectPage/_tests_/__snapshots__/ProjectPage.test.tsx.snap
src/data/projects/ClientProjects.ts

Bench 1923 add projects and extra creds
